export const qk = {
  catalogHomepage: ['catalog', 'homepage'] as const,
  catalogCategories: ['catalog', 'categories'] as const,
  catalogProducts: (queryString: string) => ['catalog', 'products', queryString] as const,
  catalogProduct: (slug: string) => ['catalog', 'product', slug] as const,
  cart: ['cart'] as const,
  ordersList: (page: number, perPage: number) => ['orders', 'list', page, perPage] as const,
  orderDetail: (id: string) => ['orders', 'detail', id] as const,
  confirmerOrders: (queryString: string) => ['confirmer', 'orders', queryString] as const,
  confirmerOrderDetail: (id: number) => ['confirmer', 'order', id] as const,
  favoritesList: ['favorites'] as const,
  adminSummary: ['admin', 'summary'] as const,
  adminOrders: (queryString: string) => ['admin', 'orders', queryString] as const,
  adminCategories: ['admin', 'categories'] as const,
  adminProducts: (queryString: string) => ['admin', 'products', queryString] as const,
  adminHomepageSections: ['admin', 'homepage', 'sections'] as const,
  adminUsers: (queryString: string) => ['admin', 'users', queryString] as const,
  adminAnalyticsSummary: ['admin', 'analytics', 'summary'] as const,
}
